steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Alrightlone
          template: classic
          base: "" # 关闭基础信息，只显示奖杯，排查干扰
          config_timezone: Asia/Shanghai
          token: ${{ secrets.METRICS_TOKEN }}

          # === 简化版成就配置 ===
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: no    # <--- 改成 no，防止因扫描私有库报错
          plugin_achievements_threshold: C   # 显示 C 级以上成就
          
          filename: github-metrics-achievements.svg